services:
  db:
    image: postgres:latest
    container_name: marketplace-backend-springboot-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: R@m_ryCnZH3pithzvExL
      POSTGRES_DB: codesumn_db
      POSTGRES_PORT: '5432'
    ports:
      - '5432:5432'
    networks:
      - marketplace-backend-springboot-network

  springboot:
    container_name: marketplace-backend-springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=mysecretkey
      - JWT_EXPIRATION_TIME=86400000
      - GITHUB_API_URL=https://api.github.com
      - SEED_DB=true
    networks:
      - marketplace-backend-springboot-network

networks:
  marketplace-backend-springboot-network:
    driver: bridge