services:
  db:
    image: postgres:17
    container_name: marketplace-backend-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: R@m_ryCnZH3pithzvExL
      POSTGRES_DB: codesumn_db
      POSTGRES_PORT: '5432'
    ports:
      - '5432:5432'
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - marketplace-network

  springboot:
    container_name: marketplace-backend-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 21
        GRADLE_VERSION: 8.8
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=mysecretkey
      - JWT_EXPIRATION_TIME=86400000
      - GITHUB_API_URL=https://api.github.com
      - SEED_DB=true
    networks:
      - marketplace-network

volumes:
  postgres-storage:
    driver: local

networks:
  marketplace-network:
    external: true