apiVersion: v1
kind: Pod
metadata:
  name: marketplace-backend-springboot-pod
  labels:
    app: marketplace-backend-springboot
spec:
  containers:
    - name: app
      image: localhost/marketplace-backend-springboot:latest
      ports:
        - containerPort: 8080
          hostPort: 8080
      env:
        - name: POSTGRES_URL
          value: 'jdbc:postgresql://marketplace-backend-springboot-db-pod:5432/codesumn_db'
        - name: POSTGRES_USER
          value: 'admin'
        - name: POSTGRES_PASSWORD
          value: 'R@m_ryCnZH3pithzvExL'
        - name: SPRING_PROFILES_ACTIVE
          value: 'production'
        - name: JWT_SECRET
          value: 'mysecretkey'
        - name: JWT_EXPIRATION_TIME
          value: '86400000'
        - name: GITHUB_API_URL
          value: 'api.github.com'
        - name: GITHUB_USER_PATH
          value: '/user'
        - name: GITHUB_SCHEME
          value: 'https'
        - name: SEED_DB
          value: 'true'
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1"
  restartPolicy: Always

#  podman build --rm --layers=false -t marketplace-backend-springboot:latest . && podman play kube pod-db.yml && podman play kube pod-app.yml