apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/portainer
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: marketplace-db-pod
  labels:
    app: marketplace-db
spec:
  initContainers:
    - name: install-locales
      image: alpine:latest
      command:
        - sh
        - -c
        - >
          apk add --no-cache musl-locales musl-locales-lang &&
          cp -r /usr/share/i18n /i18n;
      volumeMounts:
        - mountPath: /usr/share/i18n
          name: locales-volume
  containers:
    - name: postgres-db
      image: postgres:17-alpine
      ports:
        - containerPort: 5432
          hostPort: 5432
      env:
        - name: POSTGRES_USER
          value: 'admin'
        - name: POSTGRES_PASSWORD
          value: 'R@m_ryCnZH3pithzvExL'
        - name: POSTGRES_DB
          value: 'codesumn_db'
        - name: POSTGRES_PORT
          value: "5432"
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "500m"
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: portainer-pvc
    - name: locales-volume
      emptyDir: { }
  restartPolicy: Always